name:                tg-project
version:             0.1.0.0
github:              "naku0/haskell-tg-bot"
license:             BSD-3-Clause
maintainer:          "example@example.com"
copyright:           "2025 naku0"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/naku0/haskell-tg-bot.git>

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - aeson < 2.2         
  - time
  - random
  - http-conduit
  - telegram-bot-simple
  - lens
  - transformers
  - containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  tg-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tg-project

tests:
  tg-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tg-project
