name:                tg-project
version:             0.1.0.0
github:              "githubuser/tg-project"
license:             BSD-3-Clause
author:              "naku0"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tg-project#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson       # JSON
  - text        # strings
  - bytestring  # binary data
  - vector      # vector massives
  - telegram-bot-simple
  - telegram-bot-api
  - transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  tg-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tg-project

tests:
  tg-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tg-project
