resolver: lts-19.33  # проверенный и совместимый с twitter-conduit

packages:
  - .

extra-deps:
  - twitter-conduit-0.6.1

allow-newer: true  # помогает обойти мелкие несовместимости, особенно с aeson

nix:
  enable: false

# можно включить, если хочешь использовать системные пакеты:
# system-ghc: true
# install-ghc: true

